version: "3.3"
services:
  bot:
    build:
      context: ada
      dockerfile: bot.Dockerfile

  app:
    build:
      context: ada
      dockerfile: app.Dockerfile
    ports:
      - "443:443"
      - "80:80"

  db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./db:/data

networks:
  default:
    driver: bridge
