version: "3.3"
services:
  app:
    build: ./app
    ports:
      - "443:443"
      - "80:80"

  bot:
    build: ./bot

  db:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./db:/data

networks:
  default:
    driver: bridge
